// canticos.js
const CANTICOS = {
    1: "As qualidades de Jeová",
    2: "Teu nome é Jeová",
    3: "Jeová, minha força e esperança",
    4: "“Jeová é o meu Pastor”",
    5: "As obras maravilhosas de Deus",
    6: "Os céus declaram a glória de Deus",
    7: "Jeová, nossa força e poder",
    8: "Jeová é um refúgio",
    9: "Jeová é nosso Rei!",
    10: "A Jeová vou agradecer!",
    11: "A criação dá glória a Jeová",
    12: "Nosso grandioso Deus, Jeová",
    13: "Cristo, o nosso exemplo",
    14: "O novo Rei da Terra",
    15: "Louve o Filho de Jeová!",
    16: "Jeová escolheu nosso Rei",
    17: "“Eu quero!”",
    18: "Obrigado pelo resgate!",
    19: "A Ceia do Senhor",
    20: "Jeová nos deu o seu melhor",
    21: "Vou buscar primeiro o Reino",
    22: "Que venha o Reino de Deus!",
    23: "Jeová começou a reinar!",
    24: "Venham para o monte de Jeová!",
    25: "Os filhos ungidos de Jeová",
    26: "“Se fez por meus irmãos, você fez por mim”",
    27: "A vitória dos filhos de Deus",
    28: "Quem pode ser amigo de Jeová?",
    29: "Que nossa vida dê honra ao teu nome!",
    30: "Meu Deus, meu Amigo e Pai",
    31: "Ande com Deus",
    32: "Escolha o lado de Jeová!",
    33: "Deixe Jeová levar seus fardos",
    34: "Andarei em integridade",
    35: "O que é mais importante",
    36: "Proteja o coração",
    37: "Amo a Jeová de todo o coração",
    38: "Jeová vai te dar força",
    39: "Um bom nome",
    40: "Você já decidiu?",
    41: "Escuta minha oração",
    42: "Minha oração a Jeová",
    43: "Uma oração de agradecimento",
    44: "Oração de um servo aflito",
    45: "Os pensamentos do meu coração",
    46: "Obrigado, Jeová!",
    47: "Sempre a Deus vou orar",
    48: "Caminhamos sempre com Jeová",
    49: "Como alegrar a Jeová",
    50: "Minha oração de dedicação",
    51: "Dedicamos nossa vida a Jeová",
    52: "Nossa dedicação",
    53: "Pronto para pregar",
    54: "“Este é o caminho”",
    55: "Nada temam, meus amados!",
    56: "Faça da verdade a sua vida",
    57: "Pregue a todo tipo de pessoas",
    58: "Procuramos os amigos da paz",
    59: "Vamos louvar a Jeová!",
    60: "A mensagem de vida",
    61: "Avancem, Testemunhas!",
    62: "O novo cântico",
    63: "Somos Testemunhas de Jeová!",
    64: "Participamos com alegria na colheita",
    65: "Confiantes, nós vamos continuar!",
    66: "Vamos declarar as boas novas",
    67: "“Pregue a palavra”",
    68: "Plantando a semente do Reino",
    69: "Continue pregando!",
    70: "Procurem os merecedores",
    71: "Marchamos com Jeová",
    72: "Pregar as verdades do Reino",
    73: "Dá-nos coragem",
    74: "A canção do Reino",
    75: "‘Estou aqui!’",
    76: "Um sentimento especial",
    77: "Luz num mundo sombrio",
    78: "Ensine a verdade com amor",
    79: "Ensine-os a se manter firmes",
    80: "“Provem e vejam que Jeová é bom”",
    81: "A vida de um pioneiro",
    82: "‘Deixe a luz brilhar’",
    83: "“De casa em casa”",
    84: "Vamos fazer nosso melhor",
    85: "Sejam bem-vindos!",
    86: "As reuniões são o nosso lugar",
    87: "As reuniões nos encorajam",
    88: "Os teus caminhos quero entender",
    89: "Escute, obedeça e seja abençoado",
    90: "“Encorajando uns aos outros”",
    91: "Construímos com amor",
    92: "Um lugar que leva teu nome",
    93: "Abençoa nossas reuniões",
    94: "Muito obrigado pela Bíblia",
    95: "A luz clareia mais e mais",
    96: "O livro de Deus é um tesouro",
    97: "A Palavra de Deus nos ajuda a viver",
    98: "A Bíblia, um presente de Deus",
    99: "Muitos irmãos ao meu lado",
    100: "Vamos ser hospitaleiros!",
    101: "Servimos a Jeová em união",
    102: "Ajude os que estão fracos",
    103: "Os anciãos são um presente de Jeová",
    104: "Espírito santo — um presente de Deus",
    105: "“Deus é amor”",
    106: "Amor — a qualidade que é sem igual",
    107: "Jeová — o exemplo perfeito de amor",
    108: "O amor leal de Jeová",
    109: "Mostre amor de coração",
    110: "“A alegria que vem de Jeová”",
    111: "Nossos motivos de alegria",
    112: "Jeová, Deus de paz",
    113: "A paz que vem de Deus",
    114: "Seja paciente",
    115: "A paciência de Deus é salvação",
    116: "A força da bondade",
    117: "A qualidade da bondade",
    118: "Jeová, a ti pedimos mais fé",
    119: "Temos que ter fé",
    120: "Seja humilde como Jesus",
    121: "Precisamos ter autodomínio",
    122: "Vamos continuar firmes!",
    123: "Obedecemos a Jeová e à sua organização",
    124: "Sempre leais",
    125: "“Felizes os misericordiosos”",
    126: "Sempre fortes, firmes e despertos",
    127: "Que tipo de pessoa eu devo ser",
    128: "Persevere até o fim",
    129: "Eu vou perseverar",
    130: "Vamos perdoar uns aos outros",
    131: "O que Jeová uniu",
    132: "Nós somos um",
    133: "Quero ser um jovem leal",
    134: "Os filhos são uma herança de Deus",
    135: "“Seja sábio, meu filho”",
    136: "Jeová o recompensará",
    137: "Mulheres fiéis",
    138: "A beleza dos cabelos brancos",
    139: "Imagine a si mesmo no Paraíso",
    140: "Vida eterna, enfim!",
    141: "O milagre da vida",
    142: "A esperança que nos dá coragem",
    143: "Continue ativo e desperto!",
    144: "Olhe para as bênçãos!",
    145: "Deus prometeu um paraíso",
    146: "“Estou fazendo novas todas as coisas”",
    147: "A vida eterna — que bela promessa!",
    148: "Jeová é nosso Salvador",
    149: "Um cântico de vitória",
    150: "Busquem a Deus para obter livramento",
    151: "Ele chamará",
    152: "Um lugar para teu louvor",
    153: "Jeová, me dá coragem",
    154: "Eterno amor",
    155: "Nossa alegria eterna",
    156: "Olhar com fé",
    157: "Paz, enfim!",
    158: "‘Não vai se atrasar!’",
    159: "Toda a glória vou te dar",
    160: "As boas novas sobre Jesus",
    161: "Fazer tua vontade é o meu prazer",
    162: "Preciso de ti",
    163: "Felizes são esses olhos"
};